services:
  _defaults:
    autowire: true

  Sowieso\ImageStylingBundle\EventListener\ParseTemplateListener:
    arguments:
      - '@contao.routing.scope_matcher'
      - '@request_stack'
    tags:
      - { name: contao.hook, hook: parseTemplate, method: onParseTemplate }
