services:
  _defaults:
    autowire: true

  Sowieso\ImageStylingBundle\EventListener\ParseTemplateListener:
    arguments:
      - '@request_stack'
      - '@contao.routing.scope_matcher'
    tags:
      - { name: contao.hook, hook: parseTemplate, method: onParseTemplate }

  Sowieso\ImageStylingBundle\EventListener\GeneratePageListener:
    arguments:
      - '@Sowieso\ImageStylingBundle\Image\StyleCalculator'
    tags:
      - { name: contao.hook, hook: generatePage }
